version: '3'
services:
  postgres-sql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    ports:
        - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  proxy:
    image: traefik:v2.9.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  front-service:
    image: front-e
    environment:
      URL_AUTHOR: http://proxy/app2/authors
      URL_BOOK: http://proxy/app1/books
      PORT: 3001
    ports:
      - "3001:3001"
    deploy:
      replicas: 1
    expose:
      - 3001
    labels:
      - "traefik.http.routers.fronts.rule=PathPrefix(`/app3`)"
      - "traefik.http.middlewares.fronts.stripprefix.prefixes=/app3"
      - "traefik.http.routers.fronts.middlewares=fronts"

  authors-service:
    image: authors-e
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-sql:5432/distribuida
      QUARKUS_HTTP_PORT: 8080

    depends_on:
      - postgres-sql
    deploy:
      replicas: 1
    expose:
      - 8080
    labels:
      - "traefik.http.routers.authors.rule=PathPrefix(`/app2`)"
      - "traefik.http.middlewares.authors.stripprefix.prefixes=/app2"
      - "traefik.http.routers.authors.middlewares=authors"
      - "traefik.http.routers.authors.entrypoints=web"
      - "traefik.http.routers.authors.service=authors"
      - "traefik.http.services.authors.loadbalancer.server.port=8080"
      - "traefik.http.routers.authors.tls=true"

  books-service:
    image: books-e
    environment:
      DB_CONNECTION_USER: postgres
      DB_CONNECTION_PASSWORD: postgres
      DB_CONNECTION_URL: jdbc:postgresql://postgres-sql:5432/distribuida
      SERVER_PORT: 7001
      AUTHOR_URL: http://proxy/app2/authors
    depends_on:
      - postgres-sql
    deploy:
      replicas: 1
    expose:
      - 7001
    labels:
      - "traefik.http.routers.books.rule=PathPrefix(`/app1`)"
      - "traefik.http.middlewares.books.stripprefix.prefixes=/app1"
      - "traefik.http.routers.books.middlewares=books"
      - "traefik.http.routers.books.entrypoints=web"
      - "traefik.http.routers.books.service=books"
      - "traefik.http.services.books.loadbalancer.server.port=7001"
      - "traefik.http.routers.books.tls=true"

