create table if not exists public.books
(
    id integer generated by default as identity
    primary key,
    isbn   varchar(16) not null,
    title  varchar(128),
    author varchar(64),
    price  numeric(6, 2)
    );

insert into books(isbn,title,author,price) values ('11-11','title1', 1,20);
insert into books(isbn,title,author,price) values ('22-22','title2', 1,20);
insert into books(isbn,title,author,price) values ('33-33','title3', 1,20);
insert into books(isbn,title,author,price) values ('44-44','title4', 1,20);

create table if not exists public.authors
(
    id integer generated by default as identity
    primary key,
    first_name   varchar(16) not null,
    last_name  varchar(128)
    );

insert into authors(first_name, last_name) values('nombre1','ape1');
insert into authors(first_name, last_name) values('nombre2','ape2');
insert into authors(first_name, last_name) values('nombre3','ape3');
insert into authors(first_name, last_name) values('nombre4','ape4');